spring.jackson.serialization.indent_output = true
server.port=8100
server.tomcat.threads.max=200

# Import configurations
spring.config.import=optional:classpath:database.properties,\
  optional:classpath:jwt.properties
