spring.jackson.serialization.indent_output = true
server.port=8100
server.tomcat.threads.max=200

# ====================
# JPA for DB configuration
# ====================
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.datasource.url=jdbc:sqlserver://localhost:10433;databaseName=hotels_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Hotels_Password1!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ====================
# JWT
# ====================
app.jwtSecret=2xOHFIgNB29tdYPPeJb9rTJ0HmCBYk+v/ssa32TuZfE=
app.jwtExpirationMs=86400000

# ====================
# mail config
# ====================
