# ====================
# JPA for DB configuration
# ====================
spring.datasource.url=jdbc:sqlserver://localhost:10433;databaseName=hotels_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Hotels_Password1!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
